services:
  backup:
    image: offen/docker-volume-backup:v2
    container_name: docker-volume-backup
    environment:
      # AWS_S3_BUCKET_NAME: paul.diloreto.backups
      # AWS_ACCESS_KEY_ID: $S3_ACCESS_KEY
      # AWS_SECRET_ACCESS_KEY: $S3_SECRET_KEY
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 5
    volumes:
      # Network volumes:
      # Infra
      - network_caddy:/backup/caddy:ro
      - network_omada-data:/backup/omada-data:ro
      - network_omada-logs:/backup/omada-logs:ro
      - network_pihole-dnsmasq:/backup/pihole-dnsmasq:ro
      - network_pihole:/backup/pihole:ro
      # Media volumes:
      # Books
      - media_audiobookshelf-config:/backup/audiobookshelf-config:ro
      - media_audiobookshelf-metadata:/backup/audiobookshelf-metadata:ro
      - media_calibre-config:/backup/calibre-config:ro
      - media_calibre-plugins:/backup/calibre-plugins:ro
      - media_calibre-web:/backup/calibre-web:ro
      - media_prowlarr:/backup/prowlarr:ro
      - media_readarr:/backup/readarr:ro
      - media_speakarr:/backup/speakarr:ro
      - media_qbittorrent:/backup/qbittorrent:ro
      # Videos
      - media_jellyfin-config:/backup/jellyfin-config:ro
      - media_jellyfin-cache:/backup/jellyfin-cache:ro
      - media_jellyseerr:/backup/jellyseerr:ro
      - media_sonarr:/backup/sonarr:ro
      - media_radarr:/backup/radarr:ro
      - media_lidarr:/backup/lidarr:ro
      # Hass
      - hass_zwavejs2mqtt:/backup/zwavejs2mqtt:ro
      # Local folders to back up (non Docker volumes)
      - /mnt/storage/hass:/backup/hass:ro
      - /mnt/storage/lldap:/backup/lldap:ro
      - /mnt/storage/tachidesk:/backup/tachidesk:ro
      - /mnt/storage/frigate/config:/backup/frigate-config:ro
      # Local backups
      - /mnt/storage/backups:/archive
      # Required
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  # Network volumes:
  # Auth
  network_authelia:
    external: true
  network_lldap-data:
    external: true
  network_lldap-secrets:
    external: true
  # Infra
  network_caddy:
    external: true
  network_omada-data:
    external: true
  network_omada-logs:
    external: true
  network_pihole-dnsmasq:
    external: true
  network_pihole:
    external: true
  # Media volumes:
  # Books
  media_audiobookshelf-config:
    external: true
  media_audiobookshelf-metadata:
    external: true
  media_calibre-config:
    external: true
  media_calibre-plugins:
    external: true
  media_calibre-web:
    external: true
  media_readarr:
    external: true
  media_speakarr:
    external: true
  # Downloaders
  media_prowlarr:
    external: true
  media_qbittorrent:
    external: true
  # Videos
  media_jellyfin-config:
    external: true
  media_jellyfin-cache:
    external: true
  media_jellyseerr:
    external: true
  media_sonarr:
    external: true
  media_radarr:
    external: true
  media_lidarr:
    external: true
  # Hass
  hass_zwavejs2mqtt:
    external: true
