services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hass
    restart: unless-stopped
    depends_on:
      - zwave
    # Needs host network for device discovery
    network_mode: host
    privileged: true
    devices:
      - /dev/zigbee:/dev/zigbee
    volumes:
      - /mnt/storage/hass/hass:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

  zwave:
    image: zwavejs/zwavejs2mqtt:latest
    container_name: zwave
    restart: always
    tty: true
    stop_signal: SIGINT
    devices:
      - /dev/zwave:/dev/zwave
    volumes:
      - zwavejs2mqtt:/usr/src/app/store
    environment:
      TZ: $TZ
      SESSION_SECRET: $ZWAVE_SECRET
      ZWAVEJS_EXTERNAL_CONFIG: /usr/src/app/store/.config-db
    ports:
      # HA is on host network, so explicit port mapping is needed
      - 3000:3000
    networks:
      - proxy

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    environment:
      TZ: $TZ
    volumes:
      - mosquitto:/mosquitto/data
      - /mnt/storage/hass/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      # HA is on host network, so explicit port mapping is needed
      - 1883:1883

  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    networks:
      - proxy
    ports:
      - 5000:5000
      - 8554:8554
    devices:
      # Google Coral TPU m.2
      - /dev/apex_0
      # Ryzen 9 graphics
      # - /dev/dri/renderD128
      # GPU
      - /dev/dri/renderD129:/dev/dri/renderD128
    environment:
      LIBVA_DRIVER_NAME: 'radeonsi'
      # Matches env variable usage in frigate config.yml
      FRIGATE_MQTT_USER: $FRIGATE_MQTT_USER
      FRIGATE_MQTT_PASSWORD: $FRIGATE_MQTT_PASSWORD
      FRIGATE_CAM_USER: $FRIGATE_CAM_USER
      FRIGATE_BACKYARD: $FRIGATE_BACKYARD
      FRIGATE_BACKYARD_PW: $FRIGATE_BACKYARD_PW
      FRIGATE_DOORBELL: $FRIGATE_DOORBELL
      FRIGATE_DOORBELL_PW: $FRIGATE_DOORBELL_PW
      FRIGATE_FRONTYARD: $FRIGATE_FRONTYARD
      FRIGATE_FRONTYARD_PW: $FRIGATE_FRONTYARD_PW
      FRIGATE_STUDIO: $FRIGATE_STUDIO
      FRIGATE_STUDIO_PW: $FRIGATE_STUDIO_PW
      FRIGATE_BACK_HOUSE: $FRIGATE_BACK_HOUSE
      FRIGATE_BACK_HOUSE_PW: $FRIGATE_BACK_HOUSE_PW
      FRIGATE_DRIVEWAY: $FRIGATE_DRIVEWAY
      FRIGATE_DRIVEWAY_PW: $FRIGATE_DRIVEWAY_PW
      FRIGATE_BACK_STUDIO: $FRIGATE_BACK_STUDIO
      FRIGATE_BACK_STUDIO_PW: $FRIGATE_BACK_STUDIO_PW
    volumes:
      - /mnt/storage/frigate/config:/config
      - /mnt/storage/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

  steam-headless:
    container_name: steam-headless
    image: josh5/steam-headless:latest
    restart: unless-stopped
    shm_size: 2G
    ipc: host # Could also be set to 'shareable'
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    network_mode: host
    hostname: steam-deck
    extra_hosts:
      - "steam-deck:127.0.0.1"
    environment:
      # System
      - TZ=${TZ}
      - USER_LOCALES=en_US.UTF-8 UTF-8
      - DISPLAY=:55
      - SHM_SIZE=2G
      # User
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - USER_PASSWORD=${STEAM_PASSWORD}
      # Mode
      - MODE=primary
      # Web UI
      - WEB_UI_MODE=vnc
      - ENABLE_VNC_AUDIO=true
      - PORT_NOVNC_WEB=8083
      # Steam
      - ENABLE_STEAM=true
      - STEAM_ARGS=silent
      # Sunshine
      - ENABLE_SUNSHINE=false
      # Xorg
      - ENABLE_EVDEV_INPUTS=true
      - FORCE_X11_DUMMY_CONFIG=false
    devices:
      # Use the host fuse device [REQUIRED].
      - /dev/fuse
      # Add the host uinput device [REQUIRED].
      - /dev/uinput
      # Add AMD/Intel HW accelerated video encoding/decoding devices [REQUIRED].
      # NOTE: See documentation for determining which devices to configure here if you have multiple GPUs
      - /dev/dri/card1
      - /dev/dri/renderD129
    # Ensure container access to devices 13:*
    device_cgroup_rules:
      - 'c 13:* rmw'
    volumes:
      # The location of your home directory.
      # - steam-home:/home/default/:rw
      # The location where all games should be installed.
      # This path needs to be set as a library path in Steam after logging in.
      # Otherwise, Steam will store games in the home directory above.
      - /mnt/storage/games:/mnt/games/:rw
      # The Xorg socket.
      # - ${SHARED_SOCKETS_DIR}/.X11-unix/:/tmp/.X11-unix/:rw
      # Pulse audio socket.
      # - ${SHARED_SOCKETS_DIR}/pulse/:/tmp/pulse/:rw

volumes:
  zwavejs2mqtt:
  mosquitto:
  frigate:

networks:
  proxy:
    external: true

