services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hass
    restart: unless-stopped
    depends_on:
      - zwave
    # Needs host network for device discovery
    network_mode: host
    privileged: true
    devices:
      - /dev/zigbee:/dev/zigbee
    volumes:
      - /mnt/storage/hass/hass:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

  zwave:
    image: zwavejs/zwavejs2mqtt:latest
    container_name: zwave
    restart: always
    tty: true
    stop_signal: SIGINT
    devices:
      - /dev/zwave:/dev/zwave
    volumes:
      - zwavejs2mqtt:/usr/src/app/store
    environment:
      TZ: $TZ
      SESSION_SECRET: $ZWAVE_SECRET
      ZWAVEJS_EXTERNAL_CONFIG: /usr/src/app/store/.config-db
    ports:
      # HA is on host network, so explicit port mapping is needed
      - 3000:3000
    networks:
      - proxy

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    environment:
      TZ: $TZ
    volumes:
      - mosquitto:/mosquitto/data
      - /mnt/storage/hass/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      # HA is on host network, so explicit port mapping is needed
      - 1883:1883

  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    networks:
      - proxy
    ports:
      - 5000:5000
      - 8554:8554
    devices:
      # Google Coral TPU m.2
      - /dev/apex_0
      # Ryzen 9 graphics
      - /dev/dri/renderD128
    environment:
      LIBVA_DRIVER_NAME: 'radeonsi'
      # Matches env variable usage in frigate config.yml
      FRIGATE_MQTT_USER: $FRIGATE_MQTT_USER
      FRIGATE_MQTT_PASSWORD: $FRIGATE_MQTT_PASSWORD
      FRIGATE_CAM_USER: $FRIGATE_CAM_USER
      FRIGATE_BACKYARD: $FRIGATE_BACKYARD
      FRIGATE_BACKYARD_PW: $FRIGATE_BACKYARD_PW
      FRIGATE_DOORBELL: $FRIGATE_DOORBELL
      FRIGATE_DOORBELL_PW: $FRIGATE_DOORBELL_PW
      FRIGATE_FRONTYARD: $FRIGATE_FRONTYARD
      FRIGATE_FRONTYARD_PW: $FRIGATE_FRONTYARD_PW
      FRIGATE_STUDIO: $FRIGATE_STUDIO
      FRIGATE_STUDIO_PW: $FRIGATE_STUDIO_PW
      FRIGATE_BACK_HOUSE: $FRIGATE_BACK_HOUSE
      FRIGATE_BACK_HOUSE_PW: $FRIGATE_BACK_HOUSE_PW
      FRIGATE_DRIVEWAY: $FRIGATE_DRIVEWAY
      FRIGATE_DRIVEWAY_PW: $FRIGATE_DRIVEWAY_PW
      FRIGATE_BACK_STUDIO: $FRIGATE_BACK_STUDIO
      FRIGATE_BACK_STUDIO_PW: $FRIGATE_BACK_STUDIO_PW
    volumes:
      - /mnt/storage/frigate/config:/config
      - /mnt/storage/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

volumes:
  zwavejs2mqtt:
  mosquitto:
  frigate:

networks:
  proxy:
    external: true
