x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:10.11.0-rc3
    container_name: jellyfin
    restart: unless-stopped
    logging: *default-logging
    labels:
      docker-volume-backup.stop-during-backup: true
    ports:
      - 8096:8096
    volumes:
      - type: volume
        source: jellyfin-data
        target: /config
        volume:
          subpath: config
      - type: volume
        source: jellyfin-data
        target: /cache
        volume:
          subpath: cache
      - ${MEDIA_PATH}/tv_shows:/tv_shows
      - ${MEDIA_PATH}/movies:/movies
      - ${MEDIA_PATH}/anime:/anime
      - ${MEDIA_PATH}/books:/books
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
      JELLYFIN_PublishedServerUrl: "https://watch.pauld.link"
    networks:
      - proxy

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.28.0
    container_name: audiobookshelf
    restart: unless-stopped
    logging: *default-logging
    labels:
      docker-volume-backup.stop-during-backup: true
    volumes:
      - ${MEDIA_PATH}/books:/books
      - type: volume
        source: audiobookshelf-data
        target: /config
        volume:
          subpath: config
      - type: volume
        source: audiobookshelf-data
        target: /metadata
        volume:
          subpath: metadata
    networks:
      - proxy

  calibre:
    image: ghcr.io/linuxserver/calibre:8.8.0
    container_name: calibre
    restart: unless-stopped
    logging: *default-logging
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
    labels:
      docker-volume-backup.stop-during-backup: true
    volumes:
      - type: volume
        source: calibre-data
        target: /config
        volume:
          subpath: config
      - type: volume
        source: calibre-data
        target: /plugins
        volume:
          subpath: plugins
      - ${MEDIA_PATH}/books:/data/books
      - ${MEDIA_PATH}/downloads:/data/downloads
    networks:
      proxy:
        ipv4_address: 172.23.0.99

  calibre-web:
    image: linuxserver/calibre-web:0.6.24
    container_name: calibre-web
    restart: unless-stopped
    logging: *default-logging
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
      DOCKER_MODS: linuxserver/mods:universal-calibre #optional
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1 #optional
    volumes:
      - calibre-web-data:/config
      - ${MEDIA_PATH}/books:/books
    networks:
      - proxy

  # komga:
  #   image: ghcr.io/gotson/komga:1.23.1
  #   container_name: komga
  #   restart: unless-stopped
  #   logging: *default-logging
  #   user: 1000:1000
  #   volumes:
  #     - ${VOLUME_PATH}/tachidesk/downloads/mangas:/comics
  #     - ${MEDIA_PATH}/books:/books
  #     - komga-data:/config
  #   networks:
  #     - proxy

  karaoke-eternal:
    image: radrootllc/karaoke-eternal:latest
    container_name: karaoke-eternal
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - karaoke-eternal-data:/config
      - ${MEDIA_PATH}/karaoke:/mnt/karaoke
    networks:
      - proxy

volumes:
  komga-data:
  jellyfin-data:
  audiobookshelf-data:
  calibre-data:
  calibre-web-data:
  karaoke-eternal-data:
