x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:10.11.0-rc3
    container_name: jellyfin
    restart: unless-stopped
    logging: *default-logging
    labels:
      docker-volume-backup.stop-during-backup: true
    ports:
      - 8096:8096
    volumes:
      - ${VOLUME_PATH}/jellyfin/config:/config
      - ${VOLUME_PATH}/jellyfin/cache:/cache
      - ${MEDIA_PATH}/tv_shows:/tv_shows
      - ${MEDIA_PATH}/movies:/movies
      - ${MEDIA_PATH}/anime:/anime
      - ${MEDIA_PATH}/books:/books
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
      JELLYFIN_PublishedServerUrl: "https://watch.pauld.link"
    networks:
      - proxy

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.26.3
    container_name: audiobookshelf
    restart: unless-stopped
    logging: *default-logging
    labels:
      docker-volume-backup.stop-during-backup: true
    volumes:
      - ${MEDIA_PATH}/books:/books
      - ${VOLUME_PATH}/audiobookshelf/config:/config
      - ${VOLUME_PATH}/audiobookshelf/metadata:/metadata
    networks:
      - proxy

  calibre:
    image: ghcr.io/linuxserver/calibre:8.7.0
    container_name: calibre
    restart: unless-stopped
    logging: *default-logging
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
    labels:
      docker-volume-backup.stop-during-backup: true
    volumes:
      - ${VOLUME_PATH}/calibre/config:/config
      - ${VOLUME_PATH}/calibre/plugins:/plugins
      - ${MEDIA_PATH}/books:/data/books
      - ${MEDIA_PATH}/downloads:/data/downloads
    networks:
      proxy:
        ipv4_address: 172.23.0.99

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:2021.12.16
    container_name: calibre-web
    restart: unless-stopped
    logging: *default-logging
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
      DOCKER_MODS: linuxserver/mods:universal-calibre #optional
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1 #optional
    volumes:
      - ${VOLUME_PATH}/calibre-web:/config
      - ${MEDIA_PATH}/books:/books
    networks:
      - proxy

  komga:
    image: ghcr.io/gotson/komga:1.22.1
    container_name: komga
    restart: unless-stopped
    logging: *default-logging
    user: "1000:1000"
    volumes:
      - ${VOLUME_PATH}/tachidesk/downloads/mangas:/comics
      - ${MEDIA_PATH}/books:/books
      - ${VOLUME_PATH}/komga:/config
    networks:
      - proxy

  karaoke-eternal:
    image: radrootllc/karaoke-eternal:latest
    container_name: karaoke-eternal
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ${VOLUME_PATH}/karaoke-eternal/config:/config
      - ${MEDIA_PATH}/karaoke:/mnt/karaoke
    networks:
      - proxy
