x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    restart: unless-stopped
    logging: *default-logging
    labels:
      docker-volume-backup.stop-during-backup: true
    ports:
      - 8096:8096
    volumes:
      - type: volume
        source: jellyfin-data
        target: /config
        volume:
          subpath: config
      - type: volume
        source: jellyfin-data
        target: /cache
        volume:
          subpath: cache
      - ${MEDIA_PATH}/tv_shows:/tv_shows
      - ${MEDIA_PATH}/movies:/movies
      - ${MEDIA_PATH}/anime:/anime
      - ${MEDIA_PATH}/books:/books
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
      JELLYFIN_PublishedServerUrl: "https://watch.pauld.link"
    networks:
      - proxy

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.32.1
    container_name: audiobookshelf
    restart: unless-stopped
    logging: *default-logging
    labels:
      docker-volume-backup.stop-during-backup: true
    volumes:
      - ${MEDIA_PATH}/books:/books
      - type: volume
        source: audiobookshelf-data
        target: /config
        volume:
          subpath: config
      - type: volume
        source: audiobookshelf-data
        target: /metadata
        volume:
          subpath: metadata
    networks:
      - proxy

  calibre:
    image: ghcr.io/linuxserver/calibre:9.2.1
    container_name: calibre
    restart: unless-stopped
    logging: *default-logging
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
    labels:
      docker-volume-backup.stop-during-backup: true
    volumes:
      - type: volume
        source: calibre-data
        target: /config
        volume:
          subpath: config
      - type: volume
        source: calibre-data
        target: /plugins
        volume:
          subpath: plugins
      - type: volume
        source: calibre-data
        target: /books
        volume:
          subpath: books
      - ${MEDIA_PATH}/downloads:/downloads
    networks:
      proxy:
        ipv4_address: 172.23.0.99

  calibre-web-automated:
    # image: ghcr.io/crocodilestick/calibre-web-automated:V3.1.4
    # Using specific SHA for new OIDC feature until next release
    image: ghcr.io/crocodilestick/calibre-web-automated@sha256:3b6b7b9a2ff8f7bd5edcf126196cdc41d92d4f3528fdc16253a09e17c429a7ff
    container_name: calibre-web-automated
    restart: unless-stopped
    logging: *default-logging
    environment:
      PUID: 1000
      PGID: 1000
      HARDCOVER_TOKEN: $HARDCOVER_TOKEN
      # If your library is on a network share (e.g., NFS/SMB), disable WAL to reduce locking issues
      # Accepts: true/false (default: false)
      NETWORK_SHARE_MODE: false
      TZ: $TZ
      CWA_PORT_OVERRIDE: 8083
    volumes:
      - calibre-web-data:/config
      - type: volume
        source: calibre-data
        target: /calibre-library
        volume:
          subpath: books
    networks:
      - proxy

  karaoke-eternal:
    image: radrootllc/karaoke-eternal:latest
    container_name: karaoke-eternal
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - karaoke-eternal-data:/config
      - ${MEDIA_PATH}/karaoke:/mnt/karaoke
    networks:
      - proxy

volumes:
  audiobookshelf-data:
  calibre-data:
  calibre-web-data:
  jellyfin-data:
  karaoke-eternal-data:
  komga-data:
