x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  nextcloud:
    image: nextcloud:31.0.6-apache
    container_name: nextcloud
    restart: always
    logging: *default-logging
    volumes:
      - ${MEDIA_PATH}/nextcloud:/var/www/html
    environment:
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PORT: 6379
      MYSQL_PASSWORD: ${NEXTCLOUD_PW}
      MYSQL_DATABASE: ${NEXTCLOUD_DB}
      MYSQL_USER: ${NEXTCLOUD_USER}
      MYSQL_HOST: nextcloud-db
    labels:
      docker-volume-backup.stop-during-backup: true
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - proxy
      - nextcloud

  nextcloud-db:
    image: mariadb:lts-ubi9
    container_name: nextcloud-db
    restart: always
    logging: *default-logging
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ${VOLUME_PATH}/nextcloud/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${NEXTCLOUD_ROOT_PW}
      MYSQL_PASSWORD: ${NEXTCLOUD_PW}
      MYSQL_DATABASE: ${NEXTCLOUD_DB}
      MYSQL_USER: ${NEXTCLOUD_USER}
    labels:
      docker-volume-backup.stop-during-backup: true
    networks:
      - nextcloud

  nextcloud-redis:
    image: redis:8.2-m01-alpine
    container_name: nextcloud-redis
    restart: always
    logging: *default-logging
    networks:
      - nextcloud

networks:
  nextcloud:
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/16"
