services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /mnt/storage/media/tv_shows:/tv_shows
      - /mnt/storage/media/movies:/movies
    networks:
      - proxy
      - arr_network
    group_add:
      - "108"
    devices:
      - /dev/dri/renderD128

  jellyfin-vue:
    image: jellyfin/jellyfin-vue:unstable
    container_name: jellyfin-vue
    restart: unless-stopped
    environment:
      DEFAULT_SERVERS: $JELLYFIN_SERVERS
    networks:
      - proxy

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      TZ: $TZ
    volumes:
      - jellyseerr:/app/config
    networks:
      - proxy
      - arr_network

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
    volumes:
      - sonarr:/config
      - /mnt/storage/media:/data
    networks:
      - proxy
      - arr_network

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
    volumes:
      - radarr:/config
      - /mnt/storage/media:/data
    networks:
      - proxy
      - arr_network

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      PUID: 999
      PGID: 999
      TZ: $TZ
    volumes:
      - lidarr:/config
      - /mnt/storage/media:/data
    networks:
      - proxy

volumes:
  jellyfin-config:
  jellyfin-cache:
  jellyseerr:
  sonarr:
  radarr:
  lidarr:

networks:
  arr_network:
    external: true
  proxy:
    external: true
