services:
  omada-controller:
    image: mbentley/omada-controller:latest
    container_name: omada-controller
    restart: always
    ports:
      - 27001:27001/udp
      - 29810:29810/udp
      - 29811-29816:29811-29816
      - 8088:8088
      - 8043:8043
      - 8843:8843
    environment:
      TZ: $TZ
    volumes:
      - /mnt/storage/omada/data:/opt/tplink/EAPController/data
      - /mnt/storage/omada/logs:/opt/tplink/EAPController/logs
    networks:
      - proxy

  ddns-updater:
    image: ghcr.io/qdm12/ddns-updater
    container_name: ddns-updater
    restart: always
    volumes:
      - /mnt/storage/ddns-updater:/updater/data
    environment:
      TZ: $TZ
      # See: https://pkg.go.dev/time#ParseDuration
      PERIOD: 5m
      # Necessary for split dns
      RESOLVER_ADDRESS: $EXTERNAL_DNS
    networks:
      - proxy

  caddy:
    image: ghcr.io/williamjacksn/caddy-route53:latest
    container_name: caddy
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    environment:
      TZ: $TZ
      ROUTE_53_ACCESS_KEY: $ROUTE_53_ACCESS_KEY
      ROUTE_53_SECRET: $ROUTE_53_SECRET
      ROUTE_53_ZONE_ID: $ROUTE_53_ZONE_ID
    volumes:
      - /mnt/storage/caddy:/data
      - /root/docker-compose/network/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - proxy

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 81:80
    environment:
      TZ: $TZ
      DNSMASQ_USER: pihole
    volumes:
      - /mnt/storage/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /mnt/storage/pihole/config:/etc/pihole
    networks:
      - proxy

  orbital-sync:
    image: mattwebbio/orbital-sync:1
    environment:
      PRIMARY_HOST_BASE_URL: $PIHOLE_PRIMARY_URL
      PRIMARY_HOST_PASSWORD: $PIHOLE_PRIMARY_PW
      SECONDARY_HOSTS_1_BASE_URL: $PIHOLE_SECONDARY_URL
      SECONDARY_HOSTS_1_PASSWORD: $PIHOLE_SECONDARY_PW
      INTERVAL_MINUTES: 60

  wireguard:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      PASSWORD: $WIREGUARD_PW
      WG_HOST: $WIREGUARD_HOST
      WG_ALLOWED_IPS: $WG_ALLOWED_IPS
    volumes:
      - /mnt/storage/wireguard/config:/etc/wireguard
      - /lib/modules:/lib/modules

networks:
  proxy:
    external: true
