services:
  omada-controller:
    image: mbentley/omada-controller:latest
    container_name: omada-controller
    restart: always
    ports:
      - 27001:27001/udp
      - 29810:29810/udp
      - 29811-29816:29811-29816
      - 8088:8088
      - 8043:8043
      - 8843:8843
    environment:
      TZ: $TZ
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    networks:
      - proxy

  caddy:
    image: ghcr.io/williamjacksn/caddy-route53:latest
    container_name: caddy
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    environment:
      TZ: $TZ
      ROUTE_53_ACCESS_KEY: $ROUTE_53_ACCESS_KEY
      ROUTE_53_SECRET: $ROUTE_53_SECRET
    volumes:
      - /mnt/storage/docker-compose/network/Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data
    networks:
      proxy:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: $TZ
      DNSMASQ_USER: pihole
    volumes:
      - pihole-dnsmasq:/etc/dnsmasq.d
      - pihole:/etc/pihole
    networks:
      - proxy

  wireguard:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      PASSWORD: $WIREGUARD_PW
      WG_HOST: $WIREGUARD_HOST
      WG_ALLOWED_IPS: $WG_ALLOWED_IPS
    volumes:
      - /mnt/storage/wireguard/config:/etc/wireguard
      - /lib/modules:/lib/modules

volumes:
  omada-data:
  omada-logs:
  pihole-dnsmasq:
  pihole:
  caddy:

networks:
  proxy:
    external: true
