x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

x-backup-env: &backup-env
  BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
  BACKUP_PRUNING_PREFIX: backup-

x-backup-volumes: &backup-volumes
  - audiobookshelf-data:/backup/audiobookshelf-data:ro
  - authentik-data:/backup/authentik-data:ro
  - bookshelf-data:/backup/bookshelf-data:ro
  - caddy-data:/backup/caddy-data:ro
  - calibre-data:/backup/calibre-data:ro
  - calibre-web-data:/backup/calibre-web-data:ro
  - caro-tachidesk-data:/backup/caro-tachidesk-data:ro
  - ddns-updater-data:/backup/ddns-updater-data:ro
  - frigate-data:/backup/frigate-data:ro
  - gluetun-data:/backup/gluetun-data:ro
  - jellyfin-data:/backup/jellyfin-data:ro
  - jellyseer-data:/backup/jellyseer-data:ro
  - karaoke-eternal-data:/backup/karaoke-eternal-data:ro
  - mosquitto-data:/backup/mosquitto-data:ro
  - nextcloud-db-data:/backup/nextcloud-db-data:ro
  - omada-data:/backup/omada-data:ro
  - pihole-data:/backup/pihole-data:ro
  - prowlarr-data:/backup/prowlarr-data:ro
  - qbittorrent-data:/backup/qbittorrent-data:ro
  - radarr-4k-data:/backup/radarr-4k-data:ro
  - radarr-data:/backup/radarr-data:ro
  - recyclarr-data:/backup/recyclarr-data:ro
  - sonarr-data:/backup/sonarr-data:ro
  - tachidesk-data:/backup/tachidesk-data:ro
  - zwave-data:/backup/zwave-data:ro
  # Non-volumes
  - ${HASS_PATH}:/backup/hass-data:ro
  # Other files
  - ../.env:/backup/.env:ro
  - ./env:/backup/env:ro
  - ${HOME}/.ssh:/backup/.ssh:ro
  # Required
  - /var/run/docker.sock:/var/run/docker.sock:ro
  # $TZ variable not supported
  - /etc/timezone:/etc/timezone:ro
  - /etc/localtime:/etc/localtime:ro
  # Local backups
  - ${BACKUP_PATH}:/archive

services:
  omada:
    image: mbentley/omada-controller:6.1
    container_name: omada
    restart: always
    logging: *default-logging
    ports:
      - 27001:27001/udp
      - 29810:29810/udp
      - 29811-29817:29811-29817
      - 8088:8088
      - 8043:8043
      - 8843:8843
    env_file:
      - ./env/.infra.env
    environment:
      TZ: $TZ
    volumes:
      - type: volume
        source: omada-data
        target: /opt/tplink/EAPController/data
        volume:
          subpath: data
      - type: volume
        source: omada-data
        target: /opt/tplink/EAPController/logs
        volume:
          subpath: logs
    labels:
      docker-volume-backup.stop-during-backup: true
    networks:
      - proxy

  ddns-updater:
    image: ghcr.io/qdm12/ddns-updater:v2.9.0
    container_name: ddns-updater
    restart: always
    logging: *default-logging
    volumes:
      - ddns-updater-data:/updater/data
    env_file:
      - ./env/.infra.env
    environment:
      TZ: $TZ
      # See: https://pkg.go.dev/time#ParseDuration
      PERIOD: 5m
    networks:
      - proxy

  caddy:
    image: caddy:2.10.2
    container_name: caddy
    restart: always
    logging: *default-logging
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    env_file:
      - ./env/.infra.env
    environment:
      TZ: $TZ
    volumes:
      - caddy-data:/data/caddy
      - ./data/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - proxy

  pihole:
    image: pihole/pihole:2025.11.1
    container_name: pihole
    restart: always
    logging: *default-logging
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 81:80
    env_file:
      - ./env/.infra.env
    environment:
      TZ: $TZ
    volumes:
      - pihole-data:/etc/pihole
    networks:
      - proxy

  daily-local-backup:
    image: ghcr.io/offen/docker-volume-backup:v2.47.0
    container_name: daily-local-backup
    logging: *default-logging
    env_file:
      - ./env/.infra.env
    environment:
      TZ: $TZ
      <<: *backup-env
      # Every day at 6AM, except Sunday, since weekly-remote-backup will run then
      BACKUP_CRON_EXPRESSION: "0 6 * * 1-6"
      BACKUP_RETENTION_DAYS: 5
    volumes: *backup-volumes
    networks:
      - infra

  weekly-remote-backup:
    image: ghcr.io/offen/docker-volume-backup:v2.47.0
    container_name: weekly-remote-backup
    logging: *default-logging
    env_file:
      - ./env/.infra.env
    environment:
      TZ: $TZ
      <<: *backup-env
      BACKUP_CRON_EXPRESSION: "0 6 * * 0" # Every Sunday at 6AM
      BACKUP_RETENTION_DAYS: 14 # Only saving once a week
    volumes: *backup-volumes
    networks:
      - infra

volumes:
  pihole-data:
  omada-data:
  caddy-data:
  ddns-updater-data:

networks:
  infra:
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/16"
  proxy:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"
