x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  nextcloud:
    image: nextcloud:32.0.6-apache
    container_name: nextcloud
    restart: always
    logging: *default-logging
    volumes:
      - ${MEDIA_PATH}/nextcloud:/var/www/html
    env_file:
      - ./env/.nextcloud.env
    environment:
      TZ: $TZ
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PORT: 6379
      MYSQL_HOST: nextcloud-db
    labels:
      docker-volume-backup.stop-during-backup: true
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - proxy
      - nextcloud

  nextcloud-db:
    image: mariadb:lts-ubi9
    container_name: nextcloud-db
    restart: always
    logging: *default-logging
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    env_file:
      - ./env/.nextcloud.env
    environment:
      TZ: $TZ
    labels:
      docker-volume-backup.stop-during-backup: true
    networks:
      - nextcloud

  nextcloud-redis:
    image: redis:8.2-m01-alpine
    container_name: nextcloud-redis
    restart: always
    logging: *default-logging
    environment:
      TZ: $TZ
    networks:
      - nextcloud

volumes:
  nextcloud-db-data:

networks:
  nextcloud:
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/16"
