services:
  openfit:
    image: ghcr.io/soodoh/openfit:latest
    container_name: openfit
    restart: unless-stopped
    volumes:
      - openfit-data:/app/data
    env_file:
      - .shared.env
      - .openfit.env
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    networks:
      - proxy

volumes:
  openfit-data:
