services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    labels:
      docker-volume-backup.stop-during-backup: true
    ports:
      - 8096:8096
    volumes:
      - ${VOLUME_PATH}/jellyfin/config:/config
      - ${VOLUME_PATH}/jellyfin/cache:/cache
      - ${MEDIA_PATH}/tv_shows:/tv_shows
      - ${MEDIA_PATH}/movies:/movies
    group_add:
      - "108"
    devices:
      - /dev/dri/renderD128
    networks:
      - proxy

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    labels:
      docker-volume-backup.stop-during-backup: true
    volumes:
      - ${MEDIA_PATH}/books:/books
      - ${VOLUME_PATH}/audiobookshelf/config:/config
      - ${VOLUME_PATH}/audiobookshelf/metadata:/metadata
    networks:
      - proxy

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    restart: unless-stopped
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
    labels:
      docker-volume-backup.stop-during-backup: true
    volumes:
      - ${VOLUME_PATH}/calibre/config:/config
      - ${VOLUME_PATH}/calibre/plugins:/plugins
      - ${MEDIA_PATH}/books:/data/books
      - ${MEDIA_PATH}/downloads:/data/downloads
    networks:
      - proxy

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
      DOCKER_MODS: linuxserver/mods:universal-calibre #optional
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1 #optional
    volumes:
      - ${VOLUME_PATH}/calibre-web:/config
      - ${MEDIA_PATH}/books:/books
    networks:
      - proxy

  kavita:
    image: jvmilazz0/kavita
    container_name: kavita
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/tachidesk/downloads/mangas:/comics
      - ${MEDIA_PATH}/books:/books
      - ${VOLUME_PATH}/kavita:/kavita/config
    networks:
      - proxy
