services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hass
    restart: unless-stopped
    depends_on:
      - zwave
    privileged: true
    devices:
      - /dev/zigbee:/dev/zigbee
    volumes:
      - ${VOLUME_PATH}/hass/hass:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    networks:
      - hass
      - proxy

  zwave:
    image: zwavejs/zwave-js-ui:latest
    container_name: zwave
    restart: always
    tty: true
    stop_signal: SIGINT
    devices:
      - /dev/zwave:/dev/zwave
    volumes:
      - ${VOLUME_PATH}/hass/zwave-js-ui:/usr/src/app/store
    environment:
      TZ: $TZ
      SESSION_SECRET: $ZWAVE_SECRET
      ZWAVEJS_EXTERNAL_CONFIG: /usr/src/app/store/.config-db
    networks:
      - hass
      - proxy

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    environment:
      TZ: $TZ
    volumes:
      - ${VOLUME_PATH}/hass/moquitto/data:/mosquitto/data
      - ${VOLUME_PATH}/hass/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - hass

  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta4
    devices:
      # Google Coral TPU m.2
      - /dev/apex_0
      # Ryzen 9 graphics
      - /dev/dri/renderD128
    environment:
      TZ: $TZ
      LIBVA_DRIVER_NAME: 'radeonsi'
      # Matches env variable usage in frigate config.yml
      FRIGATE_MQTT_USER: $FRIGATE_MQTT_USER
      FRIGATE_MQTT_PASSWORD: $FRIGATE_MQTT_PASSWORD
      FRIGATE_CAM_USER: $FRIGATE_CAM_USER
      FRIGATE_BACKYARD: $FRIGATE_BACKYARD
      FRIGATE_BACKYARD_PW: $FRIGATE_BACKYARD_PW
      FRIGATE_DOORBELL: $FRIGATE_DOORBELL
      FRIGATE_DOORBELL_PW: $FRIGATE_DOORBELL_PW
      FRIGATE_FRONTYARD: $FRIGATE_FRONTYARD
      FRIGATE_FRONTYARD_PW: $FRIGATE_FRONTYARD_PW
      FRIGATE_STUDIO: $FRIGATE_STUDIO
      FRIGATE_STUDIO_PW: $FRIGATE_STUDIO_PW
      FRIGATE_BACK_HOUSE: $FRIGATE_BACK_HOUSE
      FRIGATE_BACK_HOUSE_PW: $FRIGATE_BACK_HOUSE_PW
      FRIGATE_DRIVEWAY: $FRIGATE_DRIVEWAY
      FRIGATE_DRIVEWAY_PW: $FRIGATE_DRIVEWAY_PW
      FRIGATE_BACK_STUDIO: $FRIGATE_BACK_STUDIO
      FRIGATE_BACK_STUDIO_PW: $FRIGATE_BACK_STUDIO_PW
    volumes:
      - ${VOLUME_PATH}/frigate:/config
      - ${MEDIA_PATH}/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    deploy:
      resources:
        limits:
          memory: 20G
    networks:
      - hass
      - proxy

networks:
  hass:
