x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  wger-web:
    image: wger/server:latest
    container_name: wger-web
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      wger-db:
        condition: service_healthy
      wger-cache:
        condition: service_healthy
    env_file:
      - ../.wger.env
    volumes:
      - ${VOLUME_PATH}/wger/static:/home/wger/static
      - ${VOLUME_PATH}/wger/media:/home/wger/media
    expose:
      - 8000
    labels:
      docker-volume-backup.stop-during-backup: true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5

  wger-db:
    image: postgres:15-alpine
    container_name: wger-db
    restart: unless-stopped
    logging: *default-logging
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
    labels:
      docker-volume-backup.stop-during-backup: true
    volumes:
      - ${VOLUME_PATH}/wger/postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wger-cache:
    image: redis
    container_name: wger-cache
    restart: unless-stopped
    logging: *default-logging
    expose:
      - 6379
    volumes:
      - ${VOLUME_PATH}/wger/redis:/data
    labels:
      docker-volume-backup.stop-during-backup: true
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  celery_worker:
    image: wger/server:latest
    container_name: wger-worker
    command: /start-worker
    restart: unless-stopped
    logging: *default-logging
    env_file:
      - ../.wger.env
    volumes:
      - ${VOLUME_PATH}/wger/media:/home/wger/media
    labels:
      docker-volume-backup.stop-during-backup: true
    depends_on:
      wger-web:
        condition: service_healthy
    healthcheck:
      test: celery -A wger inspect ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  celery_beat:
    image: wger/server:latest
    container_name: wger-beat
    command: /start-beat
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ${VOLUME_PATH}/wger/celery-beat:/home/wger/beat
    labels:
      docker-volume-backup.stop-during-backup: true
    env_file:
      - ../.wger.env
    depends_on:
      celery_worker:
        condition: service_healthy

networks:
  default:
    name: wger_network
