services:
  wger-web:
    image: wger/server:latest
    container_name: wger-web
    depends_on:
      wger-db:
        condition: service_healthy
      wger-cache:
        condition: service_healthy
    env_file:
      - ../.wger.env
    volumes:
      - ${VOLUME_PATH}/wger/static:/home/wger/static
      - ${VOLUME_PATH}/wger/media:/home/wger/media
    expose:
      - 8000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5
    restart: unless-stopped

  wger-db:
    image: postgres:15-alpine
    container_name: wger-db
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
    volumes:
      - ${VOLUME_PATH}/wger/postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  wger-cache:
    image: redis
    container_name: wger-cache
    expose:
      - 6379
    volumes:
      - ${VOLUME_PATH}/wger/redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  celery_worker:
    image: wger/server:latest
    container_name: wger-worker
    command: /start-worker
    env_file:
      - ../.wger.env
    volumes:
      - ${VOLUME_PATH}/wger/media:/home/wger/media
    depends_on:
      wger-web:
        condition: service_healthy
    healthcheck:
      test: celery -A wger inspect ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  celery_beat:
    image: wger/server:latest
    command: /start-beat
    volumes:
      - ${VOLUME_PATH}/wger/celery-beat:/home/wger/beat
    env_file:
      - ../.wger.env
    depends_on:
      celery_worker:
        condition: service_healthy

networks:
  default:
    name: wger_network
