---
- name: Rebuild Proxmox initramfs
  ansible.builtin.command:
    argv:
      - /usr/sbin/update-initramfs
      - -u
      - -k
      - all
  changed_when: true
  listen: Rebuild Proxmox initramfs

- name: Update Proxmox kernel command line
  ansible.builtin.command:
    argv:
      - /usr/sbin/update-grub
  changed_when: true
  listen: Update Proxmox kernel command line
